### ISSUE TITLE
0.200.8.1 crashes xash-rt

### ISSUE THREAD

**Issue by Mygod** [emoose/DLSSTweaks#102]
0.200.6 was working fine.

Tested with: https://github.com/sultim-t/xash-rt/releases/tag/1.0.5a

<img width="453" alt="image" src="https://github.com/emoose/DLSSTweaks/assets/3511321/72a6b589-4719-4490-9fd4-8ee08ede6aee">

**Comment by emoose** [comment]
Ah might have found the cause, because we had to add new `_nvngx.dll` exports to support Cyberpunk RR, that made the vulkan code try calling into a different `_nvngx`-only func, did add some code to try and wrap that func too, but was missing the lines to actually copy the funcptr for it over for our hook funcs to use... added fix for it in 327c631eaaa92279056ce784a692d9d69db98662

Could you see if it works with this build for you? [DLSSTweaks_0.200.8.2-beta1.zip](https://github.com/emoose/DLSSTweaks/files/12733049/DLSSTweaks_0.200.8.2-beta1.zip)

**Comment by Mygod** [comment]
Seems working now. Thank you!
