### ISSUE TITLE
MW2

### ISSUE THREAD

**Issue by SubSonix** [emoose/DLSSTweaks#57]
I'm sorry to be so useless, but can someone please explain how to get this to work with MW2?

More specifically, how to use this section: DLLPathOverrides

**Comment by SubSonix** [comment]
*UPDATE* I got it working, and as ashamed as I feel sharing this, I want to just in case someone else manages to make my mistake.

I was renaming the included .dll to nvngx_dlss.dll and I realised my mistake this morning. Instead of using the actual DLSS .dll

I blame the late hour which I was attempting to make this work last night XD

**Comment by SubSonix** [comment]
I think the main reason I was trying strange things is because I read this: https://github.com/emoose/DLSSTweaks/issues/22#issuecomment-1443624026

"but if a dlsstweaks.ini file exists next to game EXE it'll use that instead"

**Comment by SubSonix** [comment]
Slightly unrelated, but is there currently a way to set a DLSS Preset for UltraQuality?

The log makes it seem like it's currently ignored.

**Comment by SubSonix** [comment]
@emoose Sorry to tag you, but doing so for visibility instead of re-opening

**Comment by SubSonix** [comment]
Oh and just to mention, as I forgot, Ultra works in MW2

**Comment by SubSonix** [comment]
Decided to re-open so you can see it.

**Comment by emoose** [comment]
Ah sorry for late reply, don't think there's a way to set UltraQuality's preset specifically atm, if you set all the other levels presets it might affect it but haven't tried that myself.

Unfortunately with the way DLSS is told to use presets, there's not actually any slot for UltraQuality's preset to be changed, pretty annoying... I did find a way to change the presets using a different method though, but haven't found a way to set one for UQ yet.

There does seem to be more games adding "UltraQuality" mode as a setting in-game though (albeit [broken ](https://www.reddit.com/r/nvidia/comments/12c53xf/latest_like_a_dragon_ishin_update_adds_dlss/jf04mqe/) since DLSS doesn't actually support UQ, usually just ends up using a lower level unless you use DLSSTweaks to set up ratio for UQ to use)
Maybe that could mean they'll think about adding UltraQuality properly in future, so that those games wouldn't be using a broken mode any more, who knows though.

**Comment by SubSonix** [comment]
No need to apologise, I made this thread into a mess lol

I'll just play the waiting game with NVIDIA for now.

In the meantime, thank you very much for DLSSTweaks  :)
